name: Pipeline CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-docker:
    uses: org-sam/templates-ci/.github/workflows/docker-build-push.yml@main
    with:
      image_name: "ecommerce-catalog-service"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  deploy-aws-ecr:
    uses: org-sam/templates-ci/.github/workflows/publish-aws-ecr.yml@main
    with:
      runs_on: ubuntu-latest
      aws_role_last_name: dev-demo-github-oidc-infra-demo
